sudo: false

language: cpp

matrix:
  include:
    - env: PYTHON="2.7" CONDA_PY=27
      os: linux
      dist: trusty
    - env: PYTHON="3.5" CONDA_PY=35
      os: linux
      dist: trusty
    - env: PYTHON="3.6" CONDA_PY=36
      os: linux
      dist: trusty

install:
  - if [ ${PYTHON:0:1} == "2" ]; then
      if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
      else
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh -O miniconda.sh;
      fi;
      else
      if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
      fi;
    fi;
  - chmod +x miniconda.sh
  # When we are installing the 32 Bit conda on a 64 Bit system, the miniconda
  # installer will ask for a "yes" despite the -b flag, so we pipe in a yes
  - yes | ./miniconda.sh -b -p $HOME/miniconda
  #- bash miniconda.sh -b -p -f $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$HOME/miniconda/lib:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  # add channels
#  - conda config --append channels conda-forge
  #- conda config --append channels dlr-sc
#  - conda config --append channels tpaviot
  - conda config --add channels https://conda.anaconda.org/dlr-sc
  - conda config --add channels https://conda.anaconda.org/conda-forge
  - conda config --add channels https://conda.anaconda.org/tpaviot
  - conda config --add channels https://conda.anaconda.org/oce
  # Useful for debugging any issues with conda
  - conda info -a
  - conda create -n pythonocc-utils-test
  - source activate pythonocc-utils-test
  # test the *current* master
#  - export PYOCC_VERSION=0.18.2
  - conda install -n pythonocc-utils-test -c oce oce==0.18.2
  - conda install -n pythonocc-utils-test -c oce -c tpaviot/label/cd-master pythonocc-core
  - conda install -n pythonocc-utils-test -c conda-forge scipy # solve radius example


script:
  - source activate pythonocc-utils-test
  - python setup.py build install
  - cd test
  - python occutils_test.py

branches:
  only:
    - master
    - /^review/
